packages:
  - eslint
  - prettier
  - typescript
  - prettier-react
  - github
  - tailwind

catalog:
  '@types/node': ^20.14.11
  eslint: ^9.9.0
  prettier: ^3.3.3
  tsx: ^4.11.2
  typescript: ^5.5.4
  valibot: 0.37.0
  msw: ^2.3.5
  jose: ^5.6.3
  tailwindcss: ^3.4.13
catalogs:
  react18:
    react: 18.3.1
    '@types/react': ^18.3.11
